version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: migros-postgres
    environment:
      POSTGRES_DB: migros_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-testdb.sql:/docker-entrypoint-initdb.d/init-testdb.sql

  app:
    build: .
    container_name: migros-one
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/migros_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: migros-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@migrosone.com
      PGADMIN_DEFAULT_PASSWORD: migrosone
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data: